lib/bb_web/router.ex
defmodule BbWeb.Router do
  use BbWeb, :router

  import BbWeb.UserAuth
  alias BbWeb.QuestLive

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BbWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BbWeb do
    pipe_through :browser

    resources "/books", BookController
    resources "/authors", AuthorController
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", BbWeb do
    pipe_through :api

    resources "/quest_statuses", QuestStatusController, except: [:new, :edit]
    resources "/book_statuses", BookStatusController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live "/quests/new", QuestLive.Index, :new
      live "/quests/:id/edit", QuestLive.Index, :edit
      live "/quests/:id/show/edit", QuestLive.Show, :edit

      live "/quests", QuestLive.Index, :index
      live "/quests/:id", QuestLive.Show, :show

      live_dashboard "/dashboard", metrics: BbWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", BbWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", BbWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", BbWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/bb_web/live/live_helpers.ex
defmodule BbWeb.LiveHelpers do
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.quest_index_path(@socket, :index)}>
        <.live_component
          module={BbWeb.QuestLive.FormComponent}
          id={@quest.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.quest_index_path(@socket, :index)}
          quest: @quest
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
         <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

lib/bb_web/live/quest_live/form_component.ex
defmodule BbWeb.QuestLive.FormComponent do
  use BbWeb, :live_component

  alias Bb.Quests

  @doc """
  Handler for the send_update message. Adds the books to the in-memory structure
  """
  @impl true
  def update(%{action: {:selected, book}}, socket) do
    books = socket.assigns.books |> Map.put(book.id, book)
    {:ok, assign_books(socket, books)}
  end

  @impl true
  def update(%{quest: quest} = assigns, socket) do
    changeset = Quests.change_quest(quest)

    # map prevents duplicates from being added?
    # we can't use quest.books if it's a new changeset!
    # here, relying on changeset not being valid if it is new
    books_map =
      if changeset.valid?,
        do: quest.books |> Enum.into(%{}, fn book -> {book.id, book} end),
        else: %{}

    {:ok,
     socket
     |> assign(assigns)
     |> assign_books(books_map)
     |> assign(:changeset, changeset)}
  end

  def assign_books(socket, books_map) do
    socket
    |> assign(:books, books_map)
  end

  def handle_event("delete-book", %{"send" => idx}, socket) do
    {idx, _} = Integer.parse(idx)
    books_map = socket.assigns.books |> Map.delete(idx)
    {:noreply, assign_books(socket, books_map)}
  end

  @impl true
  def handle_event("validate", %{"quest" => quest_params}, socket) do
    changeset =
      socket.assigns.quest
      |> Quests.change_quest(quest_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"quest" => quest_params}, socket) do
    save_quest(socket, socket.assigns.action, quest_params)
  end

  defp save_quest(socket, :edit, quest_params) do
    books = socket.assigns.books

    case Quests.update_quest(socket.assigns.quest, quest_params, books) do
      {:ok, _quest} ->
        {:noreply,
         socket
         |> put_flash(:info, "Quest updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        IO.inspect(changeset)
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_quest(socket, :new, quest_params) do
    books = socket.assigns.books

    case Quests.create_quest(quest_params, books) do
      {:ok, _quest} ->
        {:noreply,
         socket
         |> put_flash(:info, "Quest created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/bb_web/live/quest_live/index.ex
defmodule BbWeb.QuestLive.Index do
  use BbWeb, :live_view

  alias Bb.Quests
  alias Bb.Quests.Quest

  @impl true
  def mount(_params, _session, socket) do
    {:ok,
     socket
     |> assign(:quests, list_quests())
     |> assign(:trending_books, Bb.Books.list_books())
     |> assign_categories()
     |> assign_theme()}
  end

  def assign_theme(socket) do
    socket
    |> assign(:theme, @bg_choices[:hyper])
  end

  def assign_categories(socket) do
    socket
    |> assign(:categories, [
      "Motivation & Inspiration",
      "Science",
      "health & nutrition",
      "education",
      "psychology",
      "money & investments"
    ])
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Quest")
    |> assign(:quest, Quests.get_quest_with_books!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Quest")
    |> assign(:quest, %Quest{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Quests")
    |> assign(:quest, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    quest = Quests.get_quest!(id)

    case Quests.delete_quest(quest) do
      {:ok, _} ->
        {:noreply, assign(socket, :quests, list_quests())}

      {:error, changeset} ->
        IO.inspect(changeset, label: "error deleting!!")
        {:noreply, socket}
    end
  end

  @doc """
  Callback when book is selected from the search box
  """
  @impl true
  def handle_info({:selected, book}, socket) do
    IO.inspect(book.title)
    {:noreply, socket}
  end

  defp list_quests do
    Quests.list_quests()
  end
end

lib/bb_web/live/quest_live/search_box.ex
defmodule BbWeb.QuestLive.SearchBox do
  use BbWeb, :live_component

  @impl true
  def update(_, socket) do
    {:ok, socket |> assign(:answer, "") |> assign_books()}
  end

  def assign_books(socket) do
    socket |> assign(:books, Bb.Books.list_books())
  end

  @impl true
  def handle_event("validate", %{"search" => search}, socket) do
    if String.length(search) < 1 do
      {:noreply, socket |> assign(:books, Bb.Books.list_books()) |> assign_answer(search)}
    else
      books = Bb.Books.search(search)
      {:noreply, socket |> assign(:books, books) |> assign_answer(search)}
    end
  end

  @impl true
  def handle_event("select", %{"idx" => idx}, socket) do
    {i, _} = Integer.parse(idx)

    case Enum.at(socket.assigns.books, i) do
      nil ->
        IO.puts("something went wrong...")

      book ->
        send_update(BbWeb.QuestLive.FormComponent, id: "quest-form", action: {:selected, book})
    end

    {:noreply, socket}
  end

  def assign_answer(socket, answer) do
    assign(socket, :answer, answer)
  end
end

lib/bb_web/live/quest_live/show.ex
defmodule BbWeb.QuestLive.Show do
  use BbWeb, :live_view

  alias Bb.Quests

  @bg_choices %{
    hyper: "bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500",
    cotton_candy: "bg-gradient-to-r from-pink-300 via-purple-300 to-indigo-400",
    gotham: "bg-gradient-to-r from-gray-700 via-gray-900 to-black"
  }

  @impl true
  def mount(_params, _session, socket) do
    IO.puts("we are here")
    {:ok, socket |> assign_theme()}
  end

  def assign_theme(socket) do
    socket
    |> assign(:theme, @bg_choices[:gotham])
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:quest, Quests.get_quest_with_books!(id))
     |> assign_theme()}
  end

  defp page_title(:show), do: "Show Quest"
  defp page_title(:edit), do: "Edit Quest"
end

lib/bb_web/live/quest_live/single_quest.ex
defmodule BbWeb.QuestLive.SingleQuest do
  use BbWeb, :live_component
end

lib/bb_web/live/quest_live/form_component.html.heex
<div class="p-4">
  <h2 class="text-3xl"><%= @title %></h2>
  
  <div class="flex flex-col md:flex-row gap-6">
    <.form
      let={f}
      for={@changeset}
      id="quest-form"
      phx-target={@myself}
      phx-change="validate"
      phx-submit="save"
      class="space-y-6 w-full max-w-sm">

      <div class="space-y-1">
        <%= label f, :title, class: "font-medium" %>
        <%= text_input f, :title, class: "w-full block border border-gray-200 rounded px-3 py-2 leading-6 focus:outline-none" %>
        <%= error_tag f, :title %>
      </div>

      <div class="space-y-1">
        <%= label f, :description, class: "font-medium" %>
        <%= textarea f, :description, class: "w-full block border border-gray-200 rounded px-3 py-2 leading-6 focus:outline-none" %>
        <%= error_tag f, :description %>
      </div>

      <%= error_tag f, :tags %>

      <%= for {_, book} <- @books do %>
        <div class="overflow-hidden hover:bg-zinc-50 hover:text-purple-400">
          <div class="flex items-center">
              <div class="flex-none h-16 w-10">
                <img src={book.cover} class="transition h-full object-cover hover:scale-125" />
              </div>
              <input name={"quest[books][]"} type="hidden" value={book.id}/>
              <div class="px-3 overflow-hidden">
                  <div class="flex flex-col">
                      <div class="truncate font-medium font-sans leading-loose"><%= book.title %></div>
                      <div class="font-serif text-sm">by Holly Jackson</div>
                  </div>
              </div>

              <%# delete button %>
              <div
                class="grid place-content-center mx-3 w-6 h-6 ml-auto text-red-400 cursor-pointer"
                phx-click="delete-book"
                phx-value-send={book.id}
                phx-target={@myself}
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  class="h-6 w-6"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  stroke-width="2"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M6 18L18 6M6 6l12 12"
                  />
                </svg>
              </div>
          </div>
        </div>
      <% end %>
      <div class="mt-10">
        <%= submit "Save", phx_disable_with: "Saving...", class: "button-30" %>
      </div>
    </.form>

    <div class="space-y-1 pt-6">
      <div class="font-medium">Add books</div>
      <.live_component module={BbWeb.QuestLive.SearchBox} id={:new} />
    </div>
  </div>
</div>

lib/bb_web/live/quest_live/index.html.heex
<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.quest_index_path(@socket, :index)}>
    <div class="border-4">
    <.live_component
      module={BbWeb.QuestLive.FormComponent}
      id={"quest-form"}
      title={@page_title}
      action={@live_action}
      quest={@quest}
      return_to={Routes.quest_index_path(@socket, :index)}
    />
    </div>
  </.modal>
<% end %>

<div class="grid grid-cols-3 w-full p-2 items-center">
  <div class="font-bold capitalize justify-self-start text-purple-400">
   <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
    <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16m-7 6h7" />
  </svg>
  </div>
  <div class="font-bold capitalize justify-self-center mr-1">Home</div>
  <div class="w-8 h-8 justify-self-end">
    <img class="rounded-full" src="https://source.unsplash.com/50x50" alt="my image">
  </div>
</div>

<form class="p-2 pt-4">
  <input type="string" name="search" placeholder="Titles, authors, or topics" class="border text-orange-400 font-medium rounded-xl w-full text-sm p-3 focus:outline-none focus:bg-white bg-zinc-50" phx-debounce="230"/>
</form>

<div class="flex justify-between items-center p-2 pt-4 font-bold capitalize">
  <div class="text-lg">Categories</div>
  <div class="text-sm text-gray-500">See all</div>
</div>

<div class="flex flex-wrap p-2 gap-2">
  <%= for category <- @categories do %>
    <div class="rounded-lg bg-zinc-100 p-2 px-3 text-sm font-bold text-stone-500 capitalize">
      <%= category %>
    </div>
  <% end %>
</div>

<div class="flex justify-between items-center p-2 pt-4 font-bold capitalize">
  <div class="text-lg">Trending books</div>
  <div class="text-sm text-gray-500">See all</div>
</div>

<div class="flex flex-nowrap overflow-scroll gap-4 p-2">
  <%= for book <- @trending_books do %>
  <div class="w-20 overflow-hidden shrink-0">
    <img src={book.cover}  class="w-20 h-30 rounded-lg" />
    <div class="font-bold text-sm text-gray-500 truncate"><%= book.title %></div>
  </div> 
  <% end %>
</div>

<div class="flex justify-between items-center p-2 pt-4 font-bold capitalize">
  <div class="text-lg">Quests you'll love</div>
  <div class="text-sm text-gray-500">See all</div>
</div>

<div class="flex flex-col gap-2">
<%= for quest <- @quests do %>
<div class="p-2 flex items-start">
  <div class="w-16 h-16 mr-3 shrink-0 overflow-hidden">
    <img class="rounded-lg w-full" src="https://source.unsplash.com/150x150" alt="my image">
  </div>
  <div class="truncate">
    <div class="text-lg">
      <%= live_redirect quest.title, to: Routes.quest_show_path(@socket, :show, quest), 
        class: "hover:text-purple-400 capitalize" %>
    </div>
    <div class="text-sm text-gray-400 truncate mt-1">
      <%= Bb.StringFormatter.truncate(quest.description) %>
    </div>
  </div>
</div>
<% end %>
</div>

<div class="pb-4"></div>

lib/bb_web/live/quest_live/old_index.html.heex
<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.quest_index_path(@socket, :index)}>
    <div class="border-4">
    <.live_component
      module={BbWeb.QuestLive.FormComponent}
      id={"quest-form"}
      title={@page_title}
      action={@live_action}
      quest={@quest}
      return_to={Routes.quest_index_path(@socket, :index)}
    />
    </div>
  </.modal>
<% end %>

<form class="group sticky top-0 z-50 bg-white px-4 sm:px-6 lg:px-16 shadow isolate">
  <div class="max-w-10xl mx-auto flex">
    <label for="search-input" class="flex-none pr-3 flex items-center">
      <span class="sr-only">
        Search all
        <!-- -->
        230
        <!-- -->
        icons
      </span>
      <svg
        width="24"
        height="24"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        class="text-gray-400 group-focus-within:text-gray-500 transition-colors duration-150"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
        ></path>
      </svg>
    </label>
    <input
      type="text"
      id="search-input"
      value=""
      placeholder="Search all 230 quests (Press “/” to focus)"
      class="flex-auto py-6 text-base leading-6 text-gray-500 placeholder-gray-500 focus:outline-none focus:placeholder-gray-400"
    />
    
    <span><%= live_patch "New Quest", to: Routes.quest_index_path(@socket, :new) %></span>
  </div>
</form>
<div class="px-4 sm:px-6 lg:px-16 bg-zinc-50">
  <div class="flex flex-wrap gap-4 p-6">
    <%= for quest <- @quests do %>
        <.live_component 
          module={BbWeb.QuestLive.SingleQuest}
          id={"quest-#{quest.id}"}
          quest={quest} />
    <% end %>
  </div>
</div>

lib/bb_web/live/quest_live/search_box.html.heex
<div class="max-w-sm">

<form phx-change="validate" phx-target={@myself}>
  <input type="string" name="search" value={@answer} class="border w-full p-2 focus:outline-none focus:bg-white bg-zinc-50" phx-debounce="230"/>
</form>

<%= if @books do %>
<div class="divide-y py-2 md:p-2 bg-white">
    <%= for {book, i} <- Enum.with_index(@books) do %>
        <div class="overflow-hidden hover:bg-zinc-50 hover:text-purple-400" phx-click="select" phx-value-idx={i} phx-target={@myself}>
        <div class="flex">
            <div class="flex-none h-16 w-10">
            <img src={book.cover} class="transition h-full object-cover hover:scale-125" />
            </div>

            <div class="px-3 overflow-hidden">
                <div class="flex flex-col">
                    <div class="truncate font-medium font-sans leading-loose"><%= book.title %></div>
                    <div class="font-serif text-sm">by Holly Jackson</div>
                </div>
            </div>        
        </div>
        </div>
    <% end %>
    <div class="text-center bg-zinc-50 p-2">See more results for <%= @answer %></div>
</div>
<% end %>


</div>

lib/bb_web/live/quest_live/show.html.heex
<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.quest_show_path(@socket, :show, @quest)}>
    <.live_component
      module={BbWeb.QuestLive.FormComponent}
      id={"quest-form"}
      title={@page_title}
      action={@live_action}
      quest={@quest}
      return_to={Routes.quest_show_path(@socket, :show, @quest)}
    />
  </.modal>
<% end %>

<.live_component 
  module={BbWeb.QuestLive.SingleQuest}
  id={"quest-#{@quest.id}"}
  quest={@quest}
  theme={@theme}/>

<span><%= live_patch "Edit", to: Routes.quest_show_path(@socket, :edit, @quest), class: "button" %></span> |
<span><%= live_redirect "Back", to: Routes.quest_index_path(@socket, :index) %></span>

lib/bb_web/live/quest_live/single_quest.html.heex
<div class="quest">

<div class={"#{@theme} rounded-xl"}>

<div class="p-10 flex items-start">
  <div class="w-20 h-20 mr-8 shrink-0 overflow-hidden rounded-lg">
    <img class="rounded-lg w-full" src={"https://source.unsplash.com/150x150"} alt="my image">
  </div>
  <div class="truncate">
    <div class="text-lg text-white font-bold">
      <%= @quest.title %>
    </div>
    <div class="text-sm text-gray-200 truncate mt-1 font-medium">
      by eonvocen
    </div>


    <div class="text-sm text-gray-200 truncate mt-1">
      1314 people have done this
    </div>
  </div>
</div>

</div>

<div class={"p-4 text-center text-sm leading-relaxed"}>
  <%= @quest.description %>
</div>

<div class="p-10 pb-0 pt-1">
  <div class={"rounded-full text-center w-full p-3 font-bold text-white #{@theme} shadow-xl"}>
    Join Quest
  </div>
</div>

<div class="flex justify-between items-center p-2 pt-4 font-bold capitalize">
  <div class="text-lg">Books</div>
  <div class="text-sm text-gray-500">See all</div>
</div>

<div class="flex flex-col gap-2">
<%= for book <- @quest.books do %>
<div class="p-2 flex items-start">
  <div class="w-16 h-16 mr-3 shrink-0 overflow-hidden rounded-lg">
    <img class="rounded-lg w-full" src={book.cover} alt="my image">
  </div>
  <div class="truncate">
    <div class="text-lg">
      <%= link book.title, to: Routes.book_path(@socket, :show, book), class: "hover:text-purple-400 capitalize" %>
    </div>
    <div class="text-sm text-gray-400 truncate mt-1">
      <%= Bb.StringFormatter.truncate(book.description) %>
    </div>
  </div>
</div>
<% end %>
</div>


</div>